#! /usr/bin/python3
# -*- coding:utf-8 -*-
'it is a helper to send message to your wechat friends on time'
__author__ = 'SuSu'

import itchat
import time

def sends(nicklist,msg,send_time):
    '''
    This function is based on module itchat

    The first argument is the nicknames to be sent.Generally it's a list; if there is only one person, string will also do

    The second argument is msg,which is supposed to be a string

    The third argument is the time to send.It's best a tuple made of (year,month,day,hour,minute,second).Of course,you can ignore the last few arguments. That is,if you use(2020,3), it's equal to (2020,3,1,0,0,0)
    What's more,the default time is 2000-1-1 0:00:00
    '''
    year, month, day, hour, minute, second = 2000, 1, 1, 0, 0, 0
    try:
        year=send_time[0]
        month=send_time[1]
        day=send_time[2]
        hour=send_time[3]
        minute=send_time[4]
        second=send_time[5]
    except IndexError:
        pass

    if nicklist==[] :
        return
    if type(nicklist)==str:
        nicklist=[nicklist]
    sendTime=time.mktime((year,month,day,hour,minute,second,0,0,0))
    if sendTime<time.time()-60 and nicklist:
        print('over time!')
        with open('send_log','a') as file:
            file.write('fail to send '+','.join(nicklist))
        return

    #translate nickname to wechatID
    tolist=[]
    itchat.auto_login(hotReload=True,statusStorageDir='itchat.pkl')
    for nick in nicklist:
        try:
            name=itchat.search_friends(nick)[0]['UserName']
            tolist.append((nick,name))
            print(str(year)+'.'+str(month)+'.'+str(day)+' '+str(hour)+':'+str(minute)+':'+str(second)+' '+nick+' will be sent message: "'+msg+'"')
        except IndexError:
            with open('send_log','a') as file:
                file.write(nick+' does not exist!')
            nicklist.remove(nick)

    #to avoid auto logout,every five minutes send a message
    while sendTime-time.time()>301:
        time.sleep(300)
        itchat.send(time.ctime(),toUserName='filehelper')

    #to send accurately
    try:
        time.sleep(sendTime-time.time()-1)
    except ValueError:
        pass
    while(time.time()<sendTime):
        pass

    #send 
    for nick,name in tolist:
        try:
            itchat.send(msg,toUserName=name)
        except Exception:
            with open('send_log','a') as file:
                file.write(time.ctime()+' :fail to send message " '+msg+' " to'+nick)
        nicklist.remove(nick)
        with open('send_log','a') as file:
            file.write(time.ctime()+' '+nick+' is sent message: "'+msg+'"')

if __name__ == '__main__':
    try:
        sends(['AAA','BBB','CCC],'Happy New Year!',(2018,1,1))
    except Exception as e:
        with open('send_log','a') as file:
            file.write('meet an error :'+str(e))

    import os
    os.system('poweroff')
