#! /usr/bin/python3
# -*- coding:utf-8 -*-
'it is a helper to send message to your wechat friends on time'
__author__ = 'SuSu'

import itchat
import time
import os

def sends(nicklist,msg,send_time):
    '''
    This function is based on module itchat

    The first argument is the nicknames to be sent.Generally it's a list; if there is only one person, string will also do

    The second argument is msg,which is supposed to be a string

    The third argument is the time to send.It's best a tuple made of (year,month,day,hour,minute,second).Of course,you can ignore the last few arguments. That is,if you use(2020,3), it's equal to (2020,3,1,0,0,0)
    What's more,the default time is 2000-1-1 0:00:00
    '''
    year, month, day, hour, minute, second = 2000, 1, 1, 0, 0, 0
    try:
        year=send_time[0]
        month=send_time[1]
        day=send_time[2]
        hour=send_time[3]
        minute=send_time[4]
        second=send_time[5]
    except IndexError:
        pass
    
    if nicklist==[] :
        return 
    if type(nicklist)==str:#if there is only one person to be send ,we can use a string to represent it
        nicklist=[nicklist]
    sendTime=time.mktime((year,month,day,hour,minute,second,0,0,0))
    if sendTime<time.time():
        print('over time!')
        with open('send_log','a') as file:
            file.write('fail to send '+','.join(nicklist))
        return
    
    #translate nickname to wechatID
    tolist=[]
    itchat.auto_login(hotReload=True,statusStorageDir='itchat.pkl')
    for nick in nicklist:
        try:
            name=itchat.search_friends(nick)[0]['UserName']
            tolist.append((nick,name))
            print(nick+' is to be send')
        except IndexError:
            with open('send_log','a') as file:
                file.write(nick+' does not exist!')
            nicklist.remove(nick)
    
    #to avoid auto logout,every five minutes send a message
    while sendTime-time.time()>300:
        time.sleep(300)
        itchat.send(str(time.time()),toUserName='filehelper')

    #to send accurately
    time.sleep(sendTime-time.time()-1)
    while(time.time()<sendTime):
        pass

    #send 
    for nick,name in tolist:
        try:
            itchat.send(msg,toUserName=name)
        except Exception:
            continue
        nicklist.remove(nick)
        with open('send_log','a') as file:
            file.write(year+'.'+month+'.'+day+' '+hour+':'+minute+':'+second+' '+nick+' is send message: "'+msg+'"')

    #deal with those who fail to be send
    sends(nicklist,msg,year,month,day,hour,minute,second)

if __name__ == '__main__':
    itchat.auto_login(hotReload=True,statusStorageDir='itchat.pkl')
    sends(['Swag'],'Happy Birthday!\n[This Message is send on time]',(2017,10,4))
    os.system('poweroff')#I want the computer to shutdown when sending the birthday message
